name: barcode_scan
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 3.0.1
homepage: https://github.com/mintware-de/flutter_barcode_reader

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
  protobuf: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.0


flutter:
  plugin:
    androidPackage: de.mintware.barcode_scan
    pluginClass: BarcodeScanPlugin
